field: 543cec97-94ff-4896-a9bf-3a190af25b0d
fieldLayouts:
  680bb953-0bc1-418c-ac00-284d439ffd25:
    tabs:
      -
        elements:
          -
            fieldUid: 88492753-86e3-42bc-92bd-34406ced89df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  88492753-86e3-42bc-92bd-34406ced89df:
    contentColumnType: text
    fieldGroup: null
    handle: contentBlockContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: contentBlock
name: Content
sortOrder: 2
