field: 543cec97-94ff-4896-a9bf-3a190af25b0d
fieldLayouts:
  1a89a107-bedc-4ec8-94cc-8e123c824572:
    tabs:
      -
        elements:
          -
            fieldUid: cc90da1b-77e1-4354-947d-a5c5e3c61327
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2c7a66d-5d19-433a-9528-6ddb56feff5a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cc90da1b-77e1-4354-947d-a5c5e3c61327:
    contentColumnType: string
    fieldGroup: null
    handle: imagesContent
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:05a3f35a-5608-4e9f-9bfe-1d9eb0b2c58d'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:05a3f35a-5608-4e9f-9bfe-1d9eb0b2c58d'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:05a3f35a-5608-4e9f-9bfe-1d9eb0b2c58d'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e2c7a66d-5d19-433a-9528-6ddb56feff5a:
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: images
name: Images
sortOrder: 4
