contentColumnType: string
fieldGroup: 848007d2-801a-4a71-b193-68156b4a3074
handle: tags
instructions: ''
name: Tags
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'taggroup:217fa421-1b16-4940-84ab-e12ab1d8b77b'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
